Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml
Mods/ArchipelagoTriggers.SC2Mod/Base.SC2Data/LibABFE498B.galaxy
Mods/ArchipelagoTriggers.SC2Mod/Triggers

Changes base Sentinel to 160 minerals and 3 supply! upgrade changes the cost and supply to 100 minerals and 2 supply. Is on by default.

Resource Efficiency Sentinel Upgrade added!

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/AbilData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameHotkeys.txt
Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameStrings.txt

* All infantry can now use stim from bunkers
* Can use superstim from bunkers
* Updated buttons and descriptions
This should fix _some_ of the issues in issue [#11](https://github.com/Ziktofel/Archipelago/issues/11), though I haven't covered mind-controlled units in bunkers and I'm now fairly confident they _won't_ work.
* Prior to my change, the "stim units in bunker" button would only appear if
* `(marine stimpack && !(marine super stimpack)) || (marauder stimpack && !(marauder super stimpack)) && (any unit that can stim is in the bunker)`
* With my change, any AP infantry with stim or super-stim can be in the bunker and the button will appear
* I've set the super-stimpack behaviour to dominate, so it will allow enabling / disabling auto-cast if a superstim marine and normal-stim …

sc2: Stim fixes

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/AbilData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameHotkeys.txt

* Fixed instigators not appearing in the hotkeys menu
* Linked Stalker, Instigator, and Slayer blink hotkeys to always be the same
* Linked High Templar and Archon psi storm hotkeys to always be the same
* Linked Zealot and Centurion Charge hotkeys to always be the same
* Linked Zealot and Centurion charge abilities so ordering it will cause both unit types to charge (used to only command current sub-selection)
* Moved Build Valkyrie button to column 3 where it's visible without building icons
* I swear [this is like the third time someone has asked how to build valkyries after unlocking them](https://discord.com/channels/731205301247803413/980554570075873300/1199940681628667935)
* Made sure all starport unit build buttons show up in the hotkeys menu
* Empty HotkeyAlias tags on the …

Various Hotkey fixes

---

Maps/ArchipelagoCampaign/LotV/ap_templar_s_charge.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/LotV/ap_templar_s_charge.SC2Map/Triggers

Fixing the issue reported by BicolourSnake:
> Bug Report: on Templar's Charge, the southeast Stasis Chamber sent the West Stasis Chamber location.
It's a quick fix; looks like the indices of the HybridCellUnits array just got swapped in the triggers.

sc2: Fixed swapped bonus objective locations in templar's charge

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml

Just noticed the signifier build button was using the wireframe instead of the build button. Noticed before but thought it was because there was no build button, but then I spotted it while looking into cloak icons.
New:
Old:

sc2: Used button instead of wireframe for signifier build button

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

Changes to subgroup selection, in order to have the units more used higher and to remove oddities. Heroes->casters->damage abilties->utility->blink->form changes->rest.
https://docs.google.com/spreadsheets/d/1hObgY0_T7O94AOJ6wVCElEex-sE6JKQmIMsQO2oshpA/edit#gid=1122573492

Update unit selection priorities

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

The current disruptor stats are woefully out-of-date and don't match any disruptor that has been in-game for many years. Updated the base unit's stats with what's in voidmulti.sc2mod's unitdata.xml

sc2: fix disruptor stats

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameStrings.txt

Per Hopop's request in the discord:
> can we get the bunkers to use the super stim icon when the units inside have superstim?
If units with regular stimpack are mixed in, the regular stimpack icon will dominate
https://github.com/Ziktofel/Archipelago-SC2-data/assets/31861583/aa42d4f1-afcb-445c-ae03-931be3fc7cff

sc2: Bunker superstim icons

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/EffectData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/WeaponData.xml

* Set Firebat damage point to 0 ~~(applied this to enemies as well)~~
* Mostly a gamefeel thing, the overall DPS is unchanged. Closing firebats just have to be focused slightly more to avoid damage
* AI no longer avoid disruptor shots
* This felt way less jank. It actually made disruptors _less_ powerful vs hybrid, as they couldn't zone them out indefinitely with just 4 of them
* Splash on own units now meant there was more risk to using them. With dodge behaviour, enemies would always run from your own units when sending out a nova
* AI no longer dodges corruptor shots
* This fixes [#165](https://github.com/Ziktofel/Archipelago/issues/165)
* Changed AI behaviour around swarm hosts
* Removed the AIHighPrioTarget flag -- this keeps the AI from beelining for them past armies or locusts
* …

sc2: Unit feel fixes

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml

Rebinding the hotkeys on upgrades didn't properly apply to higher levels of the same upgrade. Fixed for evo chamber, spire, and forge. The Cybernetics Core uses the base (non-AP) button data for upgrades, so should have this issue.

sc2: Properly linking upgrade hotkeys to across levels

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/GameUIData.xml

Big thanks to MindHawk for explaining in the discord how to fix this:
https://discord.com/channels/731205301247803413/980554570075873300/1224532701978300509
(2024-04-01)
This fixes one of the issues he posted on ap-sc2-data issue [#111](https://github.com/Ziktofel/Archipelago-SC2-data/issues/111)
This position would normally have 2 rock icons on it without the fix

sc2: Removed rock icons with MindHawk's recommended change

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/LightData.xml

Updated Ghost Kerrigan's portrait lighting to match vanilla HotS campaign (swarm.sc2campaign). This resolves an item within MindHawk's compiled bug reports (#111 ). There may be other light objects that are different from vanilla, I did not check anything else.
Kerrigan is no longer talking with that weird Chancellor guy. Never even heard of Darth Infestis, and frankly not interested.

sc2: Gave Kerrigan better lighting

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

Ultralisk Cavern was unable to be cancelled once building started; this PR adds the missing button back in. Tested and confirmed functional.

Adding cancel-build button to Ultralisk Cavern

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ValidatorData.xml
Mods/ArchipelagoPlayerLotV.SC2Mod/Base.SC2Data/GameData/ValidatorData.xml

Karax's production boost aura doesn't work on warp robotics facilities and warp stargates. This PR fixes that.
Issue reported by Timo here: https://discord.com/channels/731205301247803413/980554570075873300/1251054899601346661
Also thanks to Ferin for doing a quick sanity test.
Did a quick test to verify it works. Notice the behaviour icons are now visible on the warp buildings (wasn't there before):

sc2: Fixing Warp robo/stargate validators so Karax production boost works properly on salvation

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

Fixed a bug where Merc liberators couldn't siege (simple off-by-one in the abilArray override by index).
The issue was introduced in #144

sc2: Fixed a bug where Midnight Riders could not siege

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml

Tested that things don't cost minerals with twin drones and creep stomach. Didn't test the case without twin drones.

sc2: Fixed spines and spores with creep stomach and twin drones costing minerals to root

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/BehaviorData.xml

Tested on test map with scourge incubation + broodlord + viper upgrades active
-Built some corruptors
-Killed one; it correctly spawned scourges
-Morphed the others; none of them spawned scourges (as intended)

Fixing scourge incubation to not activate on morph

---

Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameStrings.txt

* Fixed an issue where Devastator Turret was called Devastation Turret in the build button
* Updated anti-armor upgrade name to Anti-Armor Munitions to avoid the confusion of having both Concussive Grenades and Punisher Grenades

sc2: Fixed devastator turret build icon name and updated anti-armour upgrade name

---

Mods/ArchipelagoTriggers.SC2Mod/Base.SC2Data/LibABFE498B.galaxy
Mods/ArchipelagoTriggers.SC2Mod/Triggers

Not sure I fixed this right and didn't test it, this is just what appeased the asserts I have on the icon repository repo and seemed to make sense if I was reading the code right.

sc2: Fixing incorrect item link in fast delivery trigger

---

Mods/ArchipelagoTriggers.SC2Mod/Base.SC2Data/LibABFE498B.galaxy
Mods/ArchipelagoTriggers.SC2Mod/Triggers

Looks like we forgot to call the unlock() function in the give tech function.

sc2: Fixing a bug where unlockScorcher was never called

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/EffectData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/WeaponData.xml
Mods/ArchipelagoPlayer.SC2Mod/Preload.xml
Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameStrings.txt

Reworking skylord to be different from a reskinned carrier. Gave it a slow but high-damage laser that deals damage in a line.
WIP

sc2: replaced skylord interceptors with a laser

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/BehaviorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/FootprintData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

Two minor fixes based on dependencies that hadn't been ported from the SwarmCampaign mod:
- Gave AP creep tumors the HotS version of base creep spread, with a shorter period and a validator that disables itself when AP_K5CreepBonuses is applied
- Imported the enhanced creep spread footprint from SwarmCampaign and pointed the Malignant Creep behavior at it

Fixing malignant creep for non-HotS missions

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/WeaponData.xml

This follows a balance discussion today in the test-games discord thread. Giving pre-war council dragoons a little more speed and +1 range, which ensures Phalanx Suit isn't just a strictly better singularity charge, and makes them more usable while maintaining the bw jank feel.

sc2: Buffing up pre-war council dragoons a little -- +1 range, +0.1 speed

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/AbilData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayerWoL.SC2Mod/Base.SC2Data/GameData/UnitData.xml

As of HotS, massive units could shatter force fields by moving into them, so that functionality has been added to AP forcefields, as well as the vanilla forcefield in the WoL submod.
Tested on Zerg smash+grab; an ultralisk could walk right through the end of the first bridge. Also tested Ravager bile; it could already smash forcefields so nothing has been changed on that end.

Adding massive-unit forcefield shatter

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/AbilData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/BehaviorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/EffectData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

- Baneling Nest now requires Hatchery instead of Spawning Pool, because it's entirely possible to unlock banelings without having access to spawning pools
- Dawnbringer lasers no longer appear on the minimap
- Reconstruction Beam no longer double-targets units who use tactical jump
- Units previously targeted by Reconstruction Beam, who somehow lost their healing effect, will no longer permanently occupy a non-healing Repair Beam; losing the healer will now remove the beam as well

Several bugfixes

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml

To fix https://github.com/Ziktofel/Archipelago/issues/232
Actual weapon range was previously working, but Jackson's Revenge uses a dummy weapon for icons that needed to have the range upgrade reflected.
I tested in game to make sure it didn't change the actual range or anything.

fix Jackson's revenge range display with advanced optics

---

Maps/ArchipelagoCampaign/WoL/ap_havens_fall.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/WoL/ap_havens_fall.SC2Map/Triggers

currently, if you load the terran version of haven's fall, you get the zerg version of the map instead.  This is due to an override in player race, presumably for testing purposes.  This change just removes that override.
I tested by loading in to all three variants of the mission after generating the map, all three races worked.

Fix Terran version of Haven's Fall

---

Maps/ArchipelagoCampaign/HotS/ap_enemy_within.SC2Map/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoTriggers.SC2Mod/Base.SC2Data/LibABFE498B.galaxy
Mods/ArchipelagoTriggers.SC2Mod/Triggers

Fixes a few bugs,
https://github.com/Ziktofel/Archipelago-SC2-data/issues/237
being able to build lurkers and impalers via morphlings on enemy within without being unlocked (added them to the remove zerg tech trigger, and unlocking adds their trigger)
not being able to able to build tyrannozors in enemy within due to no ultralisk cavern (I removed the ability to create them at all, they can't fit through vents, and ultralisks are already disabled presumably for the same reason).
fix tyrannozor subgroup priority being too high
moved dummy button to overlap with main tyrannozor merge location, didn't cause any issues, but might be confusing for future modders working with morphling.

Fixing morphling, and tyrannozor issues

---

Maps/ArchipelagoCampaign/WoL/ap_the_outlaws.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/WoL/ap_the_outlaws.SC2Map/Triggers

per discord report, when destroying the bunker as the last building on The Outlaws, you usually can't get the clear bunker check since the game ends before you can kill the bunker's units.  Simplest solution is to grant the bunker check on victory.

Add bunker check completion to victory on The Outlaws

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ValidatorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/WeaponData.xml

upgrade gives whirlyboi model
Testing took longer than expected. Turns out protoss units have some extra considerations as they have an existing model swap when going from warping in -> completed.
I did not change the weapon name, and don't intend to. The display name is not an upgradeable field, so it would involve making a whole new weapon, which then means tracking down all upgrades / references to that weapon and maintaining them, and there's risk of bugs... I don't think it's worth it for a name few people will read (unless we want to use the old 2x8 weapon, as that's already live / maintained for the other zealot variants).

sc2: non-war council Zealots now have basic model

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

Following discussion in the discord. This is a case where buttons can't be 100% consistent, because Brynhilds have afterburners and transform mode, both of which are expected in slot 2,0. It makes more sense for transform mode to take priority as it's the more impactful ability, so moved it to 2,0 and 2,1, and moved afterburners to 2,2.

sc2: Moving Brynhild fighter/assault mode button positions to match viking

---

Maps/ArchipelagoCampaign/WoL/ap_the_dig.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/WoL/ap_the_dig.SC2Map/Triggers

Reported by Alice Voltaire in the discord a few minutes ago. Looks like factions aren't checked for having units while cutscenes are running.

sc2: Making dig bases check only happen outside cinematics to fix spurious send on reaching the drill

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

Currently, there's an inconsistent and undesirable behaviour where ctrl+clicking some protoss units will include some of their variants. e.g. ctrl+click on high templar would also select signifiers. This is undesirable for casters with particular abilities or units that are different enough to warrant different macro.
In the interest of consistency, I've separated out all groups; the only remaining groups should be "primary" variant with base and vanilla versions of the unit, which should only matter when mind-control is involved.
Tested by giving myself all units, making a box-art army, and ctrl+clicking every unit type to make sure only that precise unit type was selected.

sc2: Making separate protoss units select separately under ctrl+click

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/AbilData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/AccumulatorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml
Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameStrings.txt

Makes the following changes:
fixes primal adaptation doesn't work midmission for existing units (guardian AA)
reduces guardian cost by 50 gas.
hunterling +1 armor, remove colossus collision, not light anymore.
rg bc advanced defensive matrix text didn't scale, also clarified language.
allow parasitic bomb on heroic for vipers
nydus recall text, removed reference to salvage, which sounds odd for zerg, and doesn't match the ability name.

small fixes and balance

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/AbilData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml

Giving yggdrasils transport ability while still being affected by ventral sacs. Tested by getting them, lifting/dropping without ventral sacs, then using `/send` to get ventral sacs and verifying that yggdrasils with cargo still had the cargo, could carry more, and could carry up to 16.

sc2: Giving yggdrasil 8 transport slots baseline; 16 with ventral sacs

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/EffectData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ModelData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/MoverData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/SoundData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/WeaponData.xml

Goal of changes: Make the Trireme bombers feel a little more like they're doing actual bombing runs; adjust their damage profile slightly vs smaller units (slightly weaker vs smaller stationary units, but able to deal a non-zero amount of damage vs small moving units). Also make the visual/audio effects a little more gentle to reflect the reduced impact of individual bombs.
Superficial changes (because the effects were previously scaled for the co-op version iirc, so they were built around a much bigger impact):
- Radius of explosion VFX reduced to 60% of normal
- Volume of launch and explosion SFX reduced slightly
Changes to bomber drone:
- Added minimum speed of 4 (so they'd quit stopping in midair, which means they randomly concentrate their bombs on one location)
- Increased …

Trireme bomber adjustment

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

Got all the Royal Guard units showing up in the correct category, and updated all zerg infested structures and units to the zerg category. The zerg category is so full at this point that it desperately needs a split, but I'm leaving that for another day.
The two no-icon buildings in the zerg tab are infested missile turret and bunker. I'm not sure why they don't get icons; I looked around and didn't find anything out of place in actor data, and the rootable anywhere variants probably aren't an issue or I'd expect spine and spore to display the same problem.

sc2: Updating several hotkey and glossary categories for infested and royal guard units

---

Mods/ArchipelagoPlayerLotV.SC2Mod/Base.SC2Data/GameData/UnitData.xml

This is to match vanilla behaviour. At the request of ChannelMiner on the discord. https://discord.com/channels/731205301247803413/980554570075873300/1317738689136300043
This PR is intended to affect live.
It's been long enough since I touched live that I'm not completely certain my test setup isn't contaminated by beta. The change is simple enough, though. Tested by generating and hosting on an old 0.5.0 client install I had lying around.

sc2: Increasing Artanis's selection priorty to be above Kerrigan in Infinite Cycle

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ModelData.xml
Mods/ArchipelagoTriggers.SC2Mod/Base.SC2Data/LibABFE498B.galaxy

* Fixed an issue where player scouts used the dark protoss death animation instead of the Aiur one.
* Fixed an issue where Thornshells were never locked, so the player could build them as soon as any other sc2-category merc was unlocked (necessary to unlock the submenu on the predator nest)
Tested scout death animations and verified it was the right one.
Thornshells I'm not testing as I already have them in my current playthrough. It matches the other unit lock functions by inspection.

Minor fixes

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml

Cherry-pick of #351 to live. Didn't do additional testing, it's a simple change.

sc2: Aliasing hotkeys for orbital depots and orbital command to base buildings

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml
Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameStrings.txt

Added an additional icon to Null Shroud, the Mist Wing cloak upgrade, mostly for the icon repository and web tracker.
Cleaned up unintended and unnecessary LeaderAlias entries for several upgrades.
Tested in player test map.

SC2: Add icon to Null Shroud + cleanup

---

Maps/ArchipelagoCampaign/HotS/ap_infested.SC2Map/Base.SC2Data/GameData/EffectData.xml
Maps/ArchipelagoCampaign/HotS/ap_infested.SC2Map/Base.SC2Data/GameData/UnitData.xml
Maps/ArchipelagoCampaign/HotS/ap_infested.SC2Map/Base.SC2Data/GameData/WeaponData.xml

This is responding to feedback from multiple people. The colonists on raceswapped infested just felt bad:
* They had no DPS
* They outranged bunkers, meaning they didn't tank for you
* They generally didn't do anything
Updated their stats to be a little closer to infested colonists without duplicating it entirely:
infested civilian:
35 health
8 damage / 1.2s = 6.15 DPS
melee
vanilla civilian:
30 health
5 damage / 7 + (2~5)s = 0.417 ~ 0.55 DPS
7 range
Updated civilian:
35 health
11 damage / 2 + (0~1) = 3.67 ~ 5.5 DPS
3 range
Played through the start as Terran and Protoss. The civilians felt _much_ better -- they didn't carry the mission, and required support to make any progress vs tanks or bunkers, but they tanked and helped take down those obstacles with support / sniping. The health …

sc2: Updating colonist stats on raceswapped infested so they're not useless

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ButtonData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ModelData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ValidatorData.xml
Mods/ArchipelagoPlayer.SC2Mod/enUS.SC2Data/LocalizedData/GameStrings.txt

- Updated tooltips for Psi Disrupter and Hive Mind Emulator to clarify, which races they affect
- Emphasized they don't work against Zerg baseline
(no race affected is a test state that cannot happen in an actual game)
- Fixed attack animation mismatch for Marauder and Aegis Guard (Hammer Securities were working properly)
- Fixed Scout warpin model scale
- Fixed Warp Prism unload model
- Updated Disruptor placement model
- Fixed Roach strains wireframe issue
- Fixed Highlight Tooltips for several units:
- Aegis Guard
- Blackhammer
- Disruptor
- Midnight Raiders
- Siege Breakers
- Hel's Angels
- Brynhilds
Tested in local testmap

SC2: Small fixes and polish

---

Maps/ArchipelagoCampaign/NCO/ap_in_the_enemy_s_shadow.SC2Map/Objects
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml

Set strains that inherit wireframe from parents to instead override the inherited wireframe with the correct wireframe.

Correct Two Overlayed Wireframes Displaying for Certain Zerg Strains 

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/Lib15EF4C78.galaxy

Fixed an issue where destroying initially placed gas buildings would not leave behind a geyser.

SC2: fix Gas Building issues

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/Lib15EF4C78.galaxy

fixed an issue that causes your main building to selfdestruct in all-in raceswaps

SC2: fix bug with raceswap unit replacements

---

Maps/ArchipelagoCampaign/WoL/ap_zero_hour.SC2Map/Base.SC2Data/GameData/ActorData.xml

duplicate create event in the map only.

SC2: fix Thornshell double actor in Zero Hour

---

Maps/ArchipelagoCampaign/WoL/ap_zero_hour.SC2Map/Base.SC2Data/GameData/SoundData.xml
Maps/ArchipelagoCampaign/WoL/ap_zero_hour.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/WoL/ap_zero_hour.SC2Map/Objects
Maps/ArchipelagoCampaign/WoL/ap_zero_hour.SC2Map/Triggers
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/EffectData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/RequirementNodeData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/Lib15EF4C78.galaxy
Mods/ArchipelagoTriggers.SC2Mod/Base.SC2Data/LibABFE498B.galaxy

- fixed Zero Hour (Protoss): Player was able to warp in units at the rescue locations
- adjusted the volume for some race-swap voice lines on Zero Hour
- fixed Death from Above: Spear of Adun not working properly in the first no-build section
- fixed a bug with Mist Wing Phantom Dash permanently changing Mist Wing height
- fixed Spore Crawler bio bonus button displaying when you don't have the item unlocked

SC2: Misc fixes

---

Mods/ArchipelagoTriggers.SC2Mod/Base.SC2Data/LibABFE498B.galaxy

pretty sure I fixed this before, but it didn't make it into the PR. So here we go again.

SC2: fix SoA energy in some no-built sections

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/AbilData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

This fixes trade "refunding" the resource cost of the trade by moving the cost from the training ability to the dummy units.
Trade triggers calculate the actual cost of the trade as `(number of units received) * (cost of the dummy unit)`, so this was always supposed to be the case.
I tested this by stopping all resource gathering and pressing the two receive buttons to see the exact resource changes.

Move trade cost to unit to fix trade not costing resources

---

Maps/ArchipelagoCampaign/LotV/ap_amon_s_fall.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/LotV/ap_amon_s_fall.SC2Map/Triggers
Maps/ArchipelagoCampaign/LotV/ap_into_the_void.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/LotV/ap_into_the_void.SC2Map/Objects
Maps/ArchipelagoCampaign/LotV/ap_into_the_void.SC2Map/Triggers
Maps/ArchipelagoCampaign/LotV/ap_last_stand.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/LotV/ap_last_stand.SC2Map/Triggers
Maps/ArchipelagoCampaign/LotV/ap_salvation.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/LotV/ap_salvation.SC2Map/Objects
Maps/ArchipelagoCampaign/LotV/ap_salvation.SC2Map/Triggers
Maps/ArchipelagoCampaign/LotV/ap_sky_shield.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/LotV/ap_sky_shield.SC2Map/Triggers
Maps/ArchipelagoCampaign/LotV/ap_the_host.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/LotV/ap_the_host.SC2Map/Triggers
Maps/ArchipelagoCampaign/WoL/ap_safe_haven.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/WoL/ap_safe_haven.SC2Map/Triggers
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/RequirementData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/Lib15EF4C78.galaxy

Fixed issues with auto-rally and auto-mining (in particular with ally control option) in following missions:
- Sky Shield
- Last Stand
- The Host
- Salvation
- Into the Void
- Amon's Fall
----
- Fixed disconnected Drones in Safe Haven (Zerg)
- Fixed Stalwart War Council item not displaying if you haven't found the item

Misc fixes

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ModelData.xml

Stalwart
- changed the attack animation to use the "channel" animation when standing still
- fixed an issue where the attack animation would reset to idle
- fixed an issue where the attack animation while firing on the move could cause the Stalwart to "slide"
- updated the beam visuals and added additional effects in line with the Purifier aesthetics (orange-yellow)
----
- fixed duplicate XML entry

update Stalwart attack animation

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml

- Kerrigan ghost and primal hero model now properly responds to your team color, instead of being locked into orange/purple.

SC2: Fix Kerrigan team color

---

Maps/ArchipelagoCampaign/WoL/ap_gates_of_hell.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/WoL/ap_gates_of_hell.SC2Map/Triggers
docs/debug commands.md

Fixes a bug reported on Discord. Gates of Hell lost a trigger reference for some reason, which lead to an invalid script file.
Also added the documentation for debug commands.

fix Gates of Hell broken trigger reference

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/SoundData.xml

Animation would break if build times get too fast. Added a fallback event.
also fixes a warning message from a missing sound object

fix Greater Hydralisk Den morph animation

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/Lib15EF4C78.galaxy

If a mission does not have a Spear of Adun caster unit set up (disabled in settings, no SoA item yet, no LotV mission...), the trigger to update the energy for the SoA UI will not have a valid unit for the event. This causes it to fire for every single energy change for all units in the map. Depending on the map, this can easily be several thousand times per second.
This fix turns off the trigger by default, and only turns it on, once a valid unit is set. It also adds a condition to the trigger, so that even if it is turned on, it will check, if the SoA caster unit is valid.
Tested in local testmap, made sure it works in scenarios where you have no SoA, have SoA from the start, have a no-build section without SoA or get your first SoA item over the course of a mission.

fix Spear of Adun energy display

---

Maps/ArchipelagoCampaign/LotV/ap_evil_awoken.SC2Map/MapScript.galaxy
Maps/ArchipelagoCampaign/LotV/ap_evil_awoken.SC2Map/Triggers
Maps/ArchipelagoCampaign/LotV/ap_evil_awoken.SC2Map/enUS.SC2Data/LocalizedData/TriggerStrings.txt
Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/UnitData.xml

Fixed missing Inner Radius for following units
- Vulture
- Goliath
- Dark Archon (to match regular Archon)
Caused issues with unintuitive collision behavior against hard edges like buildings and cliffs. Vultures were considered a bigger collision size than Colossus for example.
Evil Awoken: Added Debug commands
- -s2 -> Skip to Section 2
- -s3 -> Skip to Section 3
- -win -> Victory

SC2: Add debug commands to Evil Awoken

---

Mods/ArchipelagoPlayer.SC2Mod/Base.SC2Data/GameData/ActorData.xml

Fixed an issue where Infested Medic Heal would play the heal sound but never stop it.

SC2: Fix Infested Medic Heal Sound
